// songs.js — Voltage Predictor 곡 데이터 & 모델 파라미터
// 총 308곡 | R²=0.9688 | MAE=2.65콤보
// ※ enstars_regression_v3.py 로 자동 생성 — 직접 수정 비권장

const SONGS = [
  {
    "type": "Flash",
    "unit": "피네",
    "title": "오와라나이",
    "totalNotes": 158,
    "duration": "2:39",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 86.0,
    "clearNotes": 96.0
  },
  {
    "type": "Brilliant",
    "unit": "피네",
    "title": "홀리 엔젤 캐롤",
    "totalNotes": 138,
    "duration": "2:29",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Glitter",
    "unit": "피네",
    "title": "날개짓 포르티시모",
    "totalNotes": 120,
    "duration": "2:30",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 66.0,
    "clearNotes": 76.0
  },
  {
    "type": "Sparkle",
    "unit": "피네",
    "title": "Neo Sanctuary",
    "totalNotes": 161,
    "duration": "2:31",
    "etStart": 116,
    "etEnd": 131,
    "measured": 88,
    "category": "starmaker",
    "video": "https://youtu.be/w43HDVmTbgY?si=uVSQaOXt3hyTAUgF",
    "predicted": 88.0,
    "clearNotes": 98.0
  },
  {
    "type": "Flash",
    "unit": "피네",
    "title": "크로싱 하트",
    "totalNotes": 100,
    "duration": "2:41",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 55.0,
    "clearNotes": 65.0
  },
  {
    "type": "Flash",
    "unit": "피네",
    "title": "애니곡",
    "totalNotes": 140,
    "duration": "2:31",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 76.0,
    "clearNotes": 86.0
  },
  {
    "type": "Sparkle",
    "unit": "피네",
    "title": "미라클 드림 트레버",
    "totalNotes": 125,
    "duration": "2:05",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 68.0,
    "clearNotes": 78.0
  },
  {
    "type": "Brilliant",
    "unit": "피네",
    "title": "Angelic Grace",
    "totalNotes": 135,
    "duration": "2:55",
    "etStart": 66,
    "etEnd": 108,
    "measured": 76,
    "category": "starmaker",
    "video": "https://youtu.be/8BBx4GHIDG0?si=B_RB4pLW2elj2mMA",
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Brilliant",
    "unit": "피네",
    "title": "네버엔딩 스테이지",
    "totalNotes": 175,
    "duration": "2:36",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 95.0,
    "clearNotes": 105.0
  },
  {
    "type": "Sparkle",
    "unit": "피네",
    "title": "레인보우 서커스",
    "totalNotes": 138,
    "duration": "2:21",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Flash",
    "unit": "피네",
    "title": "스타라이트 퍼레이드",
    "totalNotes": 109,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 60.0,
    "clearNotes": 70.0
  },
  {
    "type": "Sparkle",
    "unit": "피네",
    "title": "The Tempest Night",
    "totalNotes": 124,
    "duration": "2:32",
    "etStart": 43,
    "etEnd": 66,
    "measured": 67,
    "category": "starmaker",
    "video": "https://youtu.be/_FWZ9hdzcAc?si=3pAErtZR7uV_DLUU",
    "predicted": 67.0,
    "clearNotes": 77.0
  },
  {
    "type": "Glitter",
    "unit": "피네",
    "title": "프리마베라",
    "totalNotes": 175,
    "duration": "2:26",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 95.0,
    "clearNotes": 105.0
  },
  {
    "type": "Brilliant",
    "unit": "피네",
    "title": "Feathers of Ark",
    "totalNotes": 171,
    "duration": "2:51",
    "etStart": 99,
    "etEnd": 135,
    "measured": 100,
    "category": "starmaker",
    "video": "https://youtu.be/6LsFhiMT7L8?si=bIVV2vwi9g5MmTm1",
    "predicted": 94.0,
    "clearNotes": 104.0
  },
  {
    "type": "Glitter",
    "unit": "피네",
    "title": "Ghostic Treat House",
    "totalNotes": 127,
    "duration": "2:47",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 69.0,
    "clearNotes": 79.0
  },
  {
    "type": "Flash",
    "unit": "피네",
    "title": "Dreaming Ocean",
    "totalNotes": 150,
    "duration": "2:45",
    "etStart": 119,
    "etEnd": 142,
    "measured": 79,
    "category": "starmaker",
    "video": "https://youtu.be/lBlFMcZZDYo?si=Yfb4-LnhlMOMrsap",
    "predicted": 83.0,
    "clearNotes": 93.0
  },
  {
    "type": "Glitter",
    "unit": "피네",
    "title": "Fairy Tale Library",
    "totalNotes": 144,
    "duration": "2:47",
    "etStart": 79,
    "etEnd": 115,
    "measured": 79,
    "category": "starmaker",
    "video": "https://youtu.be/i_9X3lDctpQ?si=cvcudSJnNbmK4U0E",
    "predicted": 80.0,
    "clearNotes": 90.0
  },
  {
    "type": "Brilliant",
    "unit": "트릭스타",
    "title": "온유스",
    "totalNotes": 97,
    "duration": "2:27",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 53.0,
    "clearNotes": 63.0
  },
  {
    "type": "Sparkle",
    "unit": "트릭스타",
    "title": "리벨리온 스타",
    "totalNotes": 111,
    "duration": "2:38",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 61.0,
    "clearNotes": 71.0
  },
  {
    "type": "Glitter",
    "unit": "트릭스타",
    "title": "인피니트 스타",
    "totalNotes": 118,
    "duration": "2:19",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 64.0,
    "clearNotes": 74.0
  },
  {
    "type": "All",
    "unit": "트릭스타",
    "title": "키세키",
    "totalNotes": 165,
    "duration": "2:35",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Brilliant",
    "unit": "트릭스타",
    "title": "하트 비터",
    "totalNotes": 125,
    "duration": "2:27",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 68.0,
    "clearNotes": 78.0
  },
  {
    "type": "Sparkle",
    "unit": "트릭스타",
    "title": "브렉스루",
    "totalNotes": 215,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 116.0,
    "clearNotes": 126.0
  },
  {
    "type": "Flash",
    "unit": "트릭스타",
    "title": "1st 싱어롱",
    "totalNotes": 157,
    "duration": "2:19",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 85.0,
    "clearNotes": 95.0
  },
  {
    "type": "Sparkle",
    "unit": "트릭스타",
    "title": "체리 해피 스트림",
    "totalNotes": 147,
    "duration": "2:07",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 80.0,
    "clearNotes": 90.0
  },
  {
    "type": "Glitter",
    "unit": "트릭스타",
    "title": "웰컴 투 트릭스타 나이트",
    "totalNotes": 107,
    "duration": "2:18",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 59.0,
    "clearNotes": 69.0
  },
  {
    "type": "Glitter",
    "unit": "트릭스타",
    "title": "행복의 노래",
    "totalNotes": 164,
    "duration": "2:43",
    "etStart": 113,
    "etEnd": 158,
    "measured": 93,
    "category": "starmaker",
    "video": "https://youtu.be/kdWHcVWhbOE?si=qpTCHv7CueVuHAxr",
    "predicted": 91.0,
    "clearNotes": 101.0
  },
  {
    "type": "Flash",
    "unit": "트릭스타",
    "title": "Unstoppable Love!",
    "totalNotes": 164,
    "duration": "2:42",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 89.0,
    "clearNotes": 99.0
  },
  {
    "type": "Brilliant",
    "unit": "트릭스타",
    "title": "리플레이",
    "totalNotes": 185,
    "duration": "2:30",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 100.0,
    "clearNotes": 110.0
  },
  {
    "type": "Flash",
    "unit": "트릭스타",
    "title": "BIGBANG REFLECTION!!",
    "totalNotes": 109,
    "duration": "2:30",
    "etStart": 66,
    "etEnd": 88,
    "measured": 58,
    "category": "starmaker",
    "video": "https://youtu.be/5H7bJ5ANRXU?si=CTWoFM6vJI78uz4D",
    "predicted": 61.0,
    "clearNotes": 71.0
  },
  {
    "type": "Glitter",
    "unit": "트릭스타",
    "title": "Finder Girl (파인더 걸)",
    "totalNotes": 136,
    "duration": "2:40",
    "etStart": 42,
    "etEnd": 53,
    "measured": 68,
    "category": "starmaker",
    "video": "https://youtu.be/AJkCL1amVks?si=chIYI3I3qK9YWfk0",
    "predicted": 72.0,
    "clearNotes": 82.0
  },
  {
    "type": "Brilliant",
    "unit": "트릭스타",
    "title": "데이드림 리얼리티",
    "totalNotes": 174,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 94.0,
    "clearNotes": 104.0
  },
  {
    "type": "Sparkle",
    "unit": "트릭스타",
    "title": "로맨틱 xday",
    "totalNotes": 158,
    "duration": "2:46",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 86.0,
    "clearNotes": 96.0
  },
  {
    "type": "Glitter",
    "unit": "트릭스타",
    "title": "와챠가나두",
    "totalNotes": 161,
    "duration": "2:48",
    "etStart": 95,
    "etEnd": 123,
    "measured": 84,
    "category": "starmaker",
    "video": "https://youtu.be/sTQfBtuHjHQ?si=vuFBXaVP20egtg4h",
    "predicted": 88.0,
    "clearNotes": 98.0
  },
  {
    "type": "Sparkle",
    "unit": "트릭스타",
    "title": "CELEBRATE!!",
    "totalNotes": 161,
    "duration": "2:45",
    "etStart": 126,
    "etEnd": 156,
    "measured": 91,
    "category": "starmaker",
    "video": "https://youtu.be/RHqdIxWxgNA?si=AEi41bRsrNOyshAj",
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Flash",
    "unit": "유성대",
    "title": "메테오 레인저",
    "totalNotes": 170,
    "duration": "2:35",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 92.0,
    "clearNotes": 102.0
  },
  {
    "type": "Sparkle",
    "unit": "유성대",
    "title": "언리미티드 파워",
    "totalNotes": 129,
    "duration": "2:16",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Glitter",
    "unit": "유성대",
    "title": "슈퍼노바 레볼루스타",
    "totalNotes": 136,
    "duration": "2:24",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 74.0,
    "clearNotes": 84.0
  },
  {
    "type": "Sparkle",
    "unit": "유성대",
    "title": "유성불꽃",
    "totalNotes": 129,
    "duration": "2:10",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Flash",
    "unit": "유성대",
    "title": "메테오 스크럼블",
    "totalNotes": 184,
    "duration": "2:37",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 100.0,
    "clearNotes": 110.0
  },
  {
    "type": "Brilliant",
    "unit": "유성대",
    "title": "청춘 Emergency",
    "totalNotes": 233,
    "duration": "2:39",
    "etStart": 112,
    "etEnd": 135,
    "measured": 133,
    "category": "starmaker",
    "video": "https://youtu.be/Y1qHQvEATuk?si=rRwJSbZ_y9NlJeG5",
    "predicted": 125.0,
    "clearNotes": 135.0
  },
  {
    "type": "Glitter",
    "unit": "유성대",
    "title": "GROWING STARRY DAYS",
    "totalNotes": 105,
    "duration": "2:12",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 58.0,
    "clearNotes": 68.0
  },
  {
    "type": "Brilliant",
    "unit": "유성대",
    "title": "NEW DAYBREAK",
    "totalNotes": 178,
    "duration": "3:01",
    "etStart": 106,
    "etEnd": 130,
    "measured": 101,
    "category": "starmaker",
    "video": "https://youtu.be/LnbOJVHwMY4?si=TNJFVTd2sPgKlYpu",
    "predicted": 97.0,
    "clearNotes": 107.0
  },
  {
    "type": "Sparkle",
    "unit": "유성대",
    "title": "Heart Heat Beat",
    "totalNotes": 154,
    "duration": "2:47",
    "etStart": 47,
    "etEnd": 75,
    "measured": 85,
    "category": "starmaker",
    "video": "https://youtu.be/BilzVweD09E?si=IFXLT82pvK3VtFfe",
    "predicted": 83.0,
    "clearNotes": 93.0
  },
  {
    "type": "Brilliant",
    "unit": "유성대",
    "title": "유메노사키 유성대가",
    "totalNotes": 164,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 89.0,
    "clearNotes": 99.0
  },
  {
    "type": "Glitter",
    "unit": "유성대",
    "title": "햄타로",
    "totalNotes": 86,
    "duration": "2:20",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 47.0,
    "clearNotes": 57.0
  },
  {
    "type": "Brilliant",
    "unit": "유성대",
    "title": "유성 할레이션",
    "totalNotes": 155,
    "duration": "2:27",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Sparkle",
    "unit": "유성대",
    "title": "열혈☆유성인법첩 (시노부 하코)",
    "totalNotes": 202,
    "duration": "2:36",
    "etStart": 100,
    "etEnd": 118,
    "measured": 115,
    "category": "starmaker",
    "video": "https://youtu.be/PQPsI-R5hqQ?si=AFXBCy2MtwIzWB4B",
    "predicted": 109.0,
    "clearNotes": 119.0
  },
  {
    "type": "Flash",
    "unit": "유성대",
    "title": "Colors Arise",
    "totalNotes": 205,
    "duration": "2:39",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 111.0,
    "clearNotes": 121.0
  },
  {
    "type": "Brilliant",
    "unit": "유성대",
    "title": "RELAX PARADISE",
    "totalNotes": 199,
    "duration": "2:50",
    "etStart": 100,
    "etEnd": 160,
    "measured": 109,
    "category": "starmaker",
    "video": "https://youtu.be/XTpbKX-HEN0?si=b9msXZh4VC0_C7ss",
    "predicted": 109.0,
    "clearNotes": 119.0
  },
  {
    "type": "Glitter",
    "unit": "유성대",
    "title": "보쿠라노 스텔라",
    "totalNotes": 150,
    "duration": "2:44",
    "etStart": 25,
    "etEnd": 32,
    "measured": 78,
    "category": "starmaker",
    "video": "https://youtu.be/C6glaT_nRp4?si=a-270axm7x7O3utV",
    "predicted": 78.0,
    "clearNotes": 88.0
  },
  {
    "type": "Brilliant",
    "unit": "유성대",
    "title": "WILDLAND SURVIVOR",
    "totalNotes": 100,
    "duration": "2:29",
    "etStart": 21,
    "etEnd": 39,
    "measured": 50,
    "category": "starmaker",
    "video": "https://youtu.be/uFJyBU4DbOI?si=2CSyGuTsGVT8FJeH",
    "predicted": 53.0,
    "clearNotes": 63.0
  },
  {
    "type": "Glitter",
    "unit": "유성대",
    "title": "OVERFLOW LIGHT UP!!!!!",
    "totalNotes": 185,
    "duration": "2:36",
    "etStart": 59,
    "etEnd": 79,
    "measured": 103,
    "category": "starmaker",
    "video": "https://youtu.be/kqELo6ZQHx8",
    "predicted": 99.0,
    "clearNotes": 109.0
  },
  {
    "type": "Sparkle",
    "unit": "알칼로이드",
    "title": "Kiss of Life",
    "totalNotes": 142,
    "duration": "2:12",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Brilliant",
    "unit": "알칼로이드",
    "title": "날개 모라토리엄",
    "totalNotes": 110,
    "duration": "2:18",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 60.0,
    "clearNotes": 70.0
  },
  {
    "type": "Glitter",
    "unit": "알칼로이드",
    "title": "Distorted Heart",
    "totalNotes": 202,
    "duration": "2:28",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 109.0,
    "clearNotes": 119.0
  },
  {
    "type": "Brilliant",
    "unit": "알칼로이드",
    "title": "You're Speculation",
    "totalNotes": 188,
    "duration": "2:18",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 102.0,
    "clearNotes": 112.0
  },
  {
    "type": "Glitter",
    "unit": "알칼로이드",
    "title": "빨치산",
    "totalNotes": 171,
    "duration": "2:42",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 93.0,
    "clearNotes": 103.0
  },
  {
    "type": "Flash",
    "unit": "알칼로이드",
    "title": "휴머노이드",
    "totalNotes": 162,
    "duration": "2:35",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 88.0,
    "clearNotes": 98.0
  },
  {
    "type": "Glitter",
    "unit": "알칼로이드",
    "title": "Black Out See Saw 워커커",
    "totalNotes": 212,
    "duration": "2:34",
    "etStart": 57,
    "etEnd": 92,
    "measured": 111,
    "category": "starmaker",
    "video": "https://youtu.be/a2cGfyx96Jg?si=uolJkqE1f82g48MH",
    "predicted": 113.0,
    "clearNotes": 123.0
  },
  {
    "type": "Brilliant",
    "unit": "알칼로이드",
    "title": "Across the universe",
    "totalNotes": 122,
    "duration": "2:52",
    "etStart": 1,
    "etEnd": 7,
    "measured": 65,
    "category": "starmaker",
    "video": "https://youtu.be/0jLzTGFVl4Y?si=b-QDAVP7v4J2eB1J",
    "predicted": 62.0,
    "clearNotes": 72.0
  },
  {
    "type": "Glitter",
    "unit": "알칼로이드",
    "title": "밤달",
    "totalNotes": 138,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Flash",
    "unit": "알칼로이드",
    "title": "Living on the edge",
    "totalNotes": 188,
    "duration": "2:11",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 102.0,
    "clearNotes": 112.0
  },
  {
    "type": "Sparkle",
    "unit": "알칼로이드",
    "title": "Believe 4 leaves",
    "totalNotes": 145,
    "duration": "2:45",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 79.0,
    "clearNotes": 89.0
  },
  {
    "type": "Flash",
    "unit": "알칼로이드",
    "title": "VERMILION",
    "totalNotes": 175,
    "duration": "2:54",
    "etStart": 127,
    "etEnd": 168,
    "measured": 96,
    "category": "starmaker",
    "video": "https://youtu.be/SHlgs0qGqUs?si=JYdJVbStRgwwPG8f",
    "predicted": 97.0,
    "clearNotes": 107.0
  },
  {
    "type": "Sparkle",
    "unit": "알칼로이드",
    "title": "UNDYING HOLY LOVE",
    "totalNotes": 156,
    "duration": "2:48",
    "etStart": 114,
    "etEnd": 132,
    "measured": 91,
    "category": "starmaker",
    "video": "https://youtu.be/3ZaWkpmu8co?si=h0LhzG8_q0GhKT6W",
    "predicted": 86.0,
    "clearNotes": 96.0
  },
  {
    "type": "Flash",
    "unit": "알칼로이드",
    "title": "SAKE OF LOVE",
    "totalNotes": 192,
    "duration": "3:12",
    "etStart": 28,
    "etEnd": 46,
    "measured": 99,
    "category": "starmaker",
    "video": "https://youtu.be/xZ8zgJmMjEY?si=3psYxq3c6zn8YLQD",
    "predicted": 101.0,
    "clearNotes": 111.0
  },
  {
    "type": "Sparkle",
    "unit": "알칼로이드",
    "title": "SunnyTrip Summer",
    "totalNotes": 127,
    "duration": "3:05",
    "etStart": 87,
    "etEnd": 97,
    "measured": 71,
    "category": "starmaker",
    "video": "https://youtu.be/Sfd-1SMuVsM?si=u7TQr70fSsLhWtjF",
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Sparkle",
    "unit": "알칼로이드",
    "title": "프레질",
    "totalNotes": 127,
    "duration": "2:14",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "starmaker",
    "video": null,
    "predicted": 69.0,
    "clearNotes": 79.0
  },
  {
    "type": "Flash",
    "unit": "피네",
    "title": "Musica Vita!",
    "totalNotes": 154,
    "duration": "2:37",
    "etStart": 102,
    "etEnd": 131,
    "measured": 83,
    "category": "starmaker",
    "video": "https://youtu.be/50kz0jhNNZY",
    "predicted": 85.0,
    "clearNotes": 95.0
  },
  {
    "type": "Flash",
    "unit": "알칼로이드",
    "title": "코토노하 칸타빌레",
    "totalNotes": 222,
    "duration": "2:25",
    "etStart": 29,
    "etEnd": 59,
    "measured": 124,
    "category": "starmaker",
    "video": "https://youtu.be/x54i9zUFLAA?si=rUnzY6MRD5uxtPH0",
    "predicted": 117.0,
    "clearNotes": 127.0
  },
  {
    "type": "Glitter",
    "unit": "Eden",
    "title": "THE GENESIS",
    "totalNotes": 144,
    "duration": "2:34",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 78.0,
    "clearNotes": 88.0
  },
  {
    "type": "Sparkle",
    "unit": "Eden",
    "title": "Dance in the Apocalypse",
    "totalNotes": 183,
    "duration": "2:18",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 99.0,
    "clearNotes": 109.0
  },
  {
    "type": "All",
    "unit": "Eden",
    "title": "키세키(キセキ)",
    "totalNotes": 165,
    "duration": "2:35",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Sparkle",
    "unit": "Eden",
    "title": "마제스틱",
    "totalNotes": 173,
    "duration": "2:41",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 94.0,
    "clearNotes": 104.0
  },
  {
    "type": "Glitter",
    "unit": "Eden",
    "title": "Awakening Myth",
    "totalNotes": 202,
    "duration": "2:27",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 109.0,
    "clearNotes": 119.0
  },
  {
    "type": "Glitter",
    "unit": "Eden",
    "title": "KEEP OUT",
    "totalNotes": 236,
    "duration": "2:56",
    "etStart": 51,
    "etEnd": 90,
    "measured": 124,
    "category": "cosmic",
    "video": "https://youtu.be/pfVXpX1aV4I?si=G8NZNZ9Z5Qd48ok1",
    "predicted": 126.0,
    "clearNotes": 136.0
  },
  {
    "type": "Sparkle",
    "unit": "Eden",
    "title": "Psyche’s Butterfly",
    "totalNotes": 174,
    "duration": "2:51",
    "etStart": 103,
    "etEnd": 132,
    "measured": 96,
    "category": "cosmic",
    "video": "https://youtu.be/4ifRZCs4jsA?si=Uz_Fps3GG7G0PLEl",
    "predicted": 95.0,
    "clearNotes": 105.0
  },
  {
    "type": "Brilliant",
    "unit": "Eden",
    "title": "楽園追放 -Faith Conquest-",
    "totalNotes": 139,
    "duration": "2:23",
    "etStart": 62,
    "etEnd": 106,
    "measured": 76,
    "category": "cosmic",
    "video": "https://youtu.be/NgUj9Obrllk?si=QyZJ4NxiZMwAT-8g",
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Flash",
    "unit": "Eden",
    "title": "EXCEED",
    "totalNotes": 219,
    "duration": "2:36",
    "etStart": 57,
    "etEnd": 83,
    "measured": 114,
    "category": "cosmic",
    "video": "https://youtu.be/xQGLhtIgjYc?si=Oo-kP3k4u-kbGYu6",
    "predicted": 117.0,
    "clearNotes": 127.0
  },
  {
    "type": "Flash",
    "unit": "Eden",
    "title": "Deep Eclipse",
    "totalNotes": 151,
    "duration": "2:46",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Brilliant",
    "unit": "Eden",
    "title": "Absolute Perfection",
    "totalNotes": 156,
    "duration": "2:49",
    "etStart": 102,
    "etEnd": 140,
    "measured": 87,
    "category": "cosmic",
    "video": "https://youtu.be/F9-sXx1Q7YU?si=1mwAtQ6cleLxRjdg",
    "predicted": 87.0,
    "clearNotes": 97.0
  },
  {
    "type": "Glitter",
    "unit": "Eden",
    "title": "원환의 리플랙션(円環のRefraction)",
    "totalNotes": 163,
    "duration": "2:40",
    "etStart": 50,
    "etEnd": 93,
    "measured": 87,
    "category": "cosmic",
    "video": "https://youtu.be/q8VFnfYCVV4?si=xWot2jbWbANgp010",
    "predicted": 88.0,
    "clearNotes": 98.0
  },
  {
    "type": "Flash",
    "unit": "Eden",
    "title": "할로윈 (大いなる愛の前に全ては巡り来る)",
    "totalNotes": 192,
    "duration": "2:43",
    "etStart": 130,
    "etEnd": 150,
    "measured": 108,
    "category": "cosmic",
    "video": "https://youtu.be/xxHW9ymTQm8?si=abDChT9U7Y-LarIN",
    "predicted": 105.0,
    "clearNotes": 115.0
  },
  {
    "type": "Flash",
    "unit": "Eve",
    "title": "Sunlit Smile!",
    "totalNotes": 133,
    "duration": "2:24",
    "etStart": 88,
    "etEnd": 118,
    "measured": 72,
    "category": "cosmic",
    "video": "https://youtu.be/-DwLLdPSAZM?si=3aiIr2M94EkyZy9D",
    "predicted": 74.0,
    "clearNotes": 84.0
  },
  {
    "type": "Brilliant",
    "unit": "Adam",
    "title": "The Beast of the End",
    "totalNotes": 161,
    "duration": "2:07",
    "etStart": 113,
    "etEnd": 157,
    "measured": 91,
    "category": "cosmic",
    "video": "https://youtu.be/o4WK5110vY4?si=N3thKNrAzMye_HLm",
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Sparkle",
    "unit": "Eve",
    "title": "Trap For You",
    "totalNotes": 192,
    "duration": "2:30",
    "etStart": 74,
    "etEnd": 119,
    "measured": 106,
    "category": "cosmic",
    "video": "https://youtu.be/5gd7Qh1DOwQ?si=2_p63RqU-nnNRS0j",
    "predicted": 104.0,
    "clearNotes": 114.0
  },
  {
    "type": "Glitter",
    "unit": "Adam",
    "title": "Ruler's Truth",
    "totalNotes": 210,
    "duration": "2:21",
    "etStart": 132,
    "etEnd": 167,
    "measured": 112,
    "category": "cosmic",
    "video": "https://youtu.be/WxT9n_aB8B8?si=ov3SlhyFUThDI0AJ",
    "predicted": 115.0,
    "clearNotes": 125.0
  },
  {
    "type": "Sparkle",
    "unit": "Adam",
    "title": "Melting Rouge Soul",
    "totalNotes": 180,
    "duration": "2:53",
    "etStart": 38,
    "etEnd": 57,
    "measured": 93,
    "category": "cosmic",
    "video": "https://youtu.be/--ND22eAXbs?si=N1-qxGNPwiul6Gw6",
    "predicted": 95.0,
    "clearNotes": 105.0
  },
  {
    "type": "Brilliant",
    "unit": "Eve",
    "title": "Ruby Love",
    "totalNotes": 185,
    "duration": "2:47",
    "etStart": 120,
    "etEnd": 159,
    "measured": 105,
    "category": "cosmic",
    "video": "https://youtu.be/mxHmoh0IUww?si=WkwyfV92PE5cQnZQ",
    "predicted": 102.0,
    "clearNotes": 112.0
  },
  {
    "type": "Brilliant",
    "unit": "Valkyrie",
    "title": "매혹극(魅惑劇)",
    "totalNotes": 129,
    "duration": "2:07",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Glitter",
    "unit": "Valkyrie",
    "title": "Mémoire Antique",
    "totalNotes": 121,
    "duration": "2:15",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 66.0,
    "clearNotes": 76.0
  },
  {
    "type": "Flash",
    "unit": "Valkyrie",
    "title": "Last Lament",
    "totalNotes": 110,
    "duration": "2:16",
    "etStart": 57,
    "etEnd": 74,
    "measured": 61,
    "category": "cosmic",
    "video": "https://youtu.be/5FeV2Qqwl34?si=99Hzg47XFiktAoFI",
    "predicted": 60.0,
    "clearNotes": 70.0
  },
  {
    "type": "Flash",
    "unit": "Valkyrie",
    "title": "오늘 밤 달의 저택에서(今宵月の館にて)",
    "totalNotes": 197,
    "duration": "2:23",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 107.0,
    "clearNotes": 117.0
  },
  {
    "type": "Sparkle",
    "unit": "Valkyrie",
    "title": "개선가(凱旋歌)",
    "totalNotes": 128,
    "duration": "2:31",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Brilliant",
    "unit": "Valkyrie",
    "title": "예찬가(礼賛歌)",
    "totalNotes": 122,
    "duration": "2:26",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 67.0,
    "clearNotes": 77.0
  },
  {
    "type": "Sparkle",
    "unit": "Valkyrie",
    "title": "축복의 Library(祝福のLibrary)",
    "totalNotes": 151,
    "duration": "2:51",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Brilliant",
    "unit": "Valkyrie",
    "title": "아름다운 나이팅게일",
    "totalNotes": 119,
    "duration": "2:48",
    "etStart": 66,
    "etEnd": 98,
    "measured": 66,
    "category": "cosmic",
    "video": "https://youtu.be/qzX_1S2Jh2s?si=r02Jq0Fy7dJpNygU",
    "predicted": 66.0,
    "clearNotes": 76.0
  },
  {
    "type": "Sparkle",
    "unit": "Valkyrie",
    "title": "홍월 커버",
    "totalNotes": 155,
    "duration": "2:49",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Glitter",
    "unit": "Valkyrie",
    "title": "Eternal Weaving",
    "totalNotes": 125,
    "duration": "2:15",
    "etStart": 84,
    "etEnd": 109,
    "measured": 68,
    "category": "cosmic",
    "video": "https://youtu.be/bziktRLR0iU?si=bvRbJTSwyZpt939H",
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Flash",
    "unit": "Valkyrie",
    "title": "Acanthe",
    "totalNotes": 159,
    "duration": "2:40",
    "etStart": 1,
    "etEnd": 29,
    "measured": 82,
    "category": "cosmic",
    "video": "https://youtu.be/YtC9FUS6HFM?si=ZRQptDv4Mlm2Znl7",
    "predicted": 83.0,
    "clearNotes": 93.0
  },
  {
    "type": "Glitter",
    "unit": "Valkyrie",
    "title": "미궁전자회랑(迷宮電子回廊)",
    "totalNotes": 144,
    "duration": "2:53",
    "etStart": 40,
    "etEnd": 58,
    "measured": 76,
    "category": "cosmic",
    "video": "https://youtu.be/R4DsM3TFwxs?si=x12g6alKsftJT_fe",
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Flash",
    "unit": "Valkyrie",
    "title": "Le temps des fleurs",
    "totalNotes": 140,
    "duration": "2:43",
    "etStart": 26,
    "etEnd": 49,
    "measured": 74,
    "category": "cosmic",
    "video": "https://youtu.be/AUsKGj2Fzw8?si=flJrASOwqXPMNrjd",
    "predicted": 74.0,
    "clearNotes": 84.0
  },
  {
    "type": "Flash",
    "unit": "Valkyrie",
    "title": "별의 명동이 울려퍼졌을 때 (星の鳴動響きし時に)",
    "totalNotes": 162,
    "duration": "2:51",
    "etStart": 83,
    "etEnd": 111,
    "measured": 90,
    "category": "cosmic",
    "video": "https://youtu.be/DiaxIJbyf34?si=RB65ei8PFi0F41CQ",
    "predicted": 88.0,
    "clearNotes": 98.0
  },
  {
    "type": "Glitter",
    "unit": "Valkyrie",
    "title": "행복론 (幸福論)",
    "totalNotes": 136,
    "duration": "2:50",
    "etStart": 40,
    "etEnd": 67,
    "measured": 74,
    "category": "cosmic",
    "video": "https://youtu.be/Adxx0A2kdjM?si=O5FvfplTEmNM5ozJ",
    "predicted": 73.0,
    "clearNotes": 83.0
  },
  {
    "type": "Flash",
    "unit": "Crazy:B",
    "title": "Crazy Roulette",
    "totalNotes": 151,
    "duration": "2:37",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Glitter",
    "unit": "Crazy:B",
    "title": "Be The Party Bee!",
    "totalNotes": 153,
    "duration": "2:16",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 83.0,
    "clearNotes": 93.0
  },
  {
    "type": "Sparkle",
    "unit": "Crazy:B",
    "title": "PARANOIA STREET",
    "totalNotes": 165,
    "duration": "2:29",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Brilliant",
    "unit": "Crazy:B",
    "title": "RISKY VENOUS",
    "totalNotes": 129,
    "duration": "2:05",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Glitter",
    "unit": "Crazy:B",
    "title": "레몬 스퀴시",
    "totalNotes": 122,
    "duration": "2:22",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 67.0,
    "clearNotes": 77.0
  },
  {
    "type": "Flash",
    "unit": "Crazy:B",
    "title": "Noisy:Beep",
    "totalNotes": 161,
    "duration": "2:33",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 87.0,
    "clearNotes": 97.0
  },
  {
    "type": "Glitter",
    "unit": "Crazy:B",
    "title": "NA NA NA SUMMER NIGHT BeeAT",
    "totalNotes": 153,
    "duration": "2:43",
    "etStart": 46,
    "etEnd": 77,
    "measured": 83,
    "category": "cosmic",
    "video": "https://youtu.be/ueARJH0lOpo",
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Brilliant",
    "unit": "Crazy:B",
    "title": "Foolish Alien",
    "totalNotes": 183,
    "duration": "2:31",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 99.0,
    "clearNotes": 109.0
  },
  {
    "type": "Brilliant",
    "unit": "Crazy:B",
    "title": "U.S.A",
    "totalNotes": 181,
    "duration": "2:40",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 98.0,
    "clearNotes": 108.0
  },
  {
    "type": "Brilliant",
    "unit": "Crazy:B",
    "title": "Honeycomb Summer",
    "totalNotes": 172,
    "duration": "2:34",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 93.0,
    "clearNotes": 103.0
  },
  {
    "type": "Sparkle",
    "unit": "Crazy:B",
    "title": "아리아드네 (指先のアリアドネ)",
    "totalNotes": 151,
    "duration": "2:42",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Flash",
    "unit": "Crazy:B",
    "title": "Helter-Spider",
    "totalNotes": 132,
    "duration": "2:31",
    "etStart": 45,
    "etEnd": 76,
    "measured": 73,
    "category": "cosmic",
    "video": "https://youtu.be/7Z90uJrZ6hE?si=pO4-opLZiJ-x4hMc",
    "predicted": 72.0,
    "clearNotes": 82.0
  },
  {
    "type": "Sparkle",
    "unit": "Crazy:B",
    "title": "Crazy Anthem",
    "totalNotes": 183,
    "duration": "2:46",
    "etStart": 57,
    "etEnd": 71,
    "measured": 90,
    "category": "cosmic",
    "video": "https://youtu.be/qkNuxf18RuI?si=5sTvCN81PP7Gac_C",
    "predicted": 97.0,
    "clearNotes": 107.0
  },
  {
    "type": "Flash",
    "unit": "Crazy:B",
    "title": "SAKE OF LOVE (사케 오브 러브)",
    "totalNotes": 192,
    "duration": "3:12",
    "etStart": 28,
    "etEnd": 46,
    "measured": 99,
    "category": "cosmic",
    "video": "https://youtu.be/xZ8zgJmMjEY?si=o2PAmywwvB5TIhSq",
    "predicted": 101.0,
    "clearNotes": 111.0
  },
  {
    "type": "Flash",
    "unit": "Crazy:B",
    "title": "UTAKATA DANCE FLOOR",
    "totalNotes": 145,
    "duration": "2:37",
    "etStart": 90,
    "etEnd": 140,
    "measured": 79,
    "category": "cosmic",
    "video": "https://youtu.be/KKOmwmcLAJc?si=rCPw5XBjTdNEdANm",
    "predicted": 81.0,
    "clearNotes": 91.0
  },
  {
    "type": "Glitter",
    "unit": "Crazy:B",
    "title": "KING",
    "totalNotes": 217,
    "duration": "2:24",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 117.0,
    "clearNotes": 127.0
  },
  {
    "type": "Brilliant",
    "unit": "Crazy:B",
    "title": "니키 감사제 (ハニートラップ・マリアージュ)",
    "totalNotes": 194,
    "duration": "2:48",
    "etStart": 117,
    "etEnd": 147,
    "measured": 104,
    "category": "cosmic",
    "video": "https://youtu.be/iay7pagyxjU?si=VMR_M1XZY8mszB2R",
    "predicted": 106.0,
    "clearNotes": 116.0
  },
  {
    "type": "Sparkle",
    "unit": "2wink",
    "title": "환영☆투・윙크 기예단",
    "totalNotes": 128,
    "duration": "2:16",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Flash",
    "unit": "2wink",
    "title": "TRICK with TREAT!!(with UNDEAD)",
    "totalNotes": 184,
    "duration": "2:37",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 100.0,
    "clearNotes": 110.0
  },
  {
    "type": "Glitter",
    "unit": "2wink",
    "title": "Play “Tag”",
    "totalNotes": 125,
    "duration": "2:23",
    "etStart": 92,
    "etEnd": 110,
    "measured": 69,
    "category": "cosmic",
    "video": "https://youtu.be/VHeL3Sqkato?si=-f06LAiDWw4_qlVZ",
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Brilliant",
    "unit": "2wink",
    "title": "하트 프리즘・시메트리",
    "totalNotes": 202,
    "duration": "2:37",
    "etStart": 140,
    "etEnd": 172,
    "measured": 111,
    "category": "cosmic",
    "video": "https://youtu.be/8igMnhpcuh0?si=aSSG9db_pQlY21zp",
    "predicted": 111.0,
    "clearNotes": 121.0
  },
  {
    "type": "Brilliant",
    "unit": "2wink",
    "title": "Mischievous Party Time!!",
    "totalNotes": 195,
    "duration": "2:31",
    "etStart": 122,
    "etEnd": 145,
    "measured": 105,
    "category": "cosmic",
    "video": "https://youtu.be/n2Rk_IoB5zM?si=R1HA1Qx8yBzlADKV",
    "predicted": 106.0,
    "clearNotes": 116.0
  },
  {
    "type": "Glitter",
    "unit": "2wink",
    "title": "레몬 스쿼시 치어스",
    "totalNotes": 122,
    "duration": "2:22",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 67.0,
    "clearNotes": 77.0
  },
  {
    "type": "Glitter",
    "unit": "2wink",
    "title": "슈가 스파이스",
    "totalNotes": 178,
    "duration": "2:31",
    "etStart": 116,
    "etEnd": 125,
    "measured": 97,
    "category": "cosmic",
    "video": "https://youtu.be/Cg2Fk383B4E?si=9b6iAO2LnkMwtRMs",
    "predicted": 96.0,
    "clearNotes": 106.0
  },
  {
    "type": "Brilliant",
    "unit": "2wink",
    "title": "공중전(トゥウィンクル空中戦)",
    "totalNotes": 239,
    "duration": "2:27",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 129.0,
    "clearNotes": 139.0
  },
  {
    "type": "Glitter",
    "unit": "2wink",
    "title": "POLYPHONIC WORLD",
    "totalNotes": 129,
    "duration": "2:25",
    "etStart": 66,
    "etEnd": 115,
    "measured": 74,
    "category": "cosmic",
    "video": "https://youtu.be/JXRfwxSW2uM?si=GKeAlZB7lIBj5jc5",
    "predicted": 73.0,
    "clearNotes": 83.0
  },
  {
    "type": "Flash",
    "unit": "2wink",
    "title": "2winkle Star Beat☆",
    "totalNotes": 184,
    "duration": "2:29",
    "etStart": 42,
    "etEnd": 71,
    "measured": 102,
    "category": "cosmic",
    "video": "https://youtu.be/PuRUA2vcJ1A?si=UWOJjOYtOgK_akES",
    "predicted": 98.0,
    "clearNotes": 108.0
  },
  {
    "type": "Flash",
    "unit": "2wink",
    "title": "텔 유어 월드",
    "totalNotes": 116,
    "duration": "2:44",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 63.0,
    "clearNotes": 73.0
  },
  {
    "type": "Flash",
    "unit": "2wink",
    "title": "Fighting Dreamer",
    "totalNotes": 141,
    "duration": "2:30",
    "etStart": 50,
    "etEnd": 68,
    "measured": 76,
    "category": "cosmic",
    "video": "https://youtu.be/lxzSzDkWGzc?si=6GaDYUesvrfU3tO3",
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Sparkle",
    "unit": "2wink",
    "title": "Swee2wink Love Letter",
    "totalNotes": 156,
    "duration": "2:35",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 85.0,
    "clearNotes": 95.0
  },
  {
    "type": "Sparkle",
    "unit": "2wink",
    "title": "Turbulent Storm",
    "totalNotes": 147,
    "duration": "2:36",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "cosmic",
    "video": null,
    "predicted": 80.0,
    "clearNotes": 90.0
  },
  {
    "type": "Flash",
    "unit": "2wink",
    "title": "럽미 몬스터(Love×me⇄monsteR)",
    "totalNotes": 217,
    "duration": "2:34",
    "etStart": 136,
    "etEnd": 177,
    "measured": 116,
    "category": "cosmic",
    "video": "https://youtu.be/C853sWzXfWI?si=ad2MiORPV0daDFAR",
    "predicted": 119.0,
    "clearNotes": 129.0
  },
  {
    "type": "Flash",
    "unit": "2wink",
    "title": "Twin Wedding Vows",
    "totalNotes": 104,
    "duration": "2:23",
    "etStart": 48,
    "etEnd": 82,
    "measured": 57,
    "category": "cosmic",
    "video": "https://youtu.be/OvVvv1qL6mA?si=iOjtGIA8H3mWQJpU",
    "predicted": 58.0,
    "clearNotes": 68.0
  },
  {
    "type": "Flash",
    "unit": "2wink",
    "title": "감사제(来来☆2winkイリュージョン)",
    "totalNotes": 181,
    "duration": "2:21",
    "etStart": 106,
    "etEnd": 146,
    "measured": 99,
    "category": "cosmic",
    "video": "https://youtu.be/Sag56BWbyBM?si=cQOEFl2-KAFcKEjf",
    "predicted": 99.0,
    "clearNotes": 109.0
  },
  {
    "type": "Flash",
    "unit": "UNDEAD",
    "title": "Melody in the Dark",
    "totalNotes": 152,
    "duration": "2:37",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/eoQE_n5ITSU?si=rdxhHahQ6kgSC5mi",
    "predicted": 83.0,
    "clearNotes": 93.0
  },
  {
    "type": "Glitter",
    "unit": "UNDEAD",
    "title": "Valentine Eve's Nightmare",
    "totalNotes": 164,
    "duration": "2:30",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/OMv6CprdegM?si=20wVqjLyD_tJ_aBg",
    "predicted": 89.0,
    "clearNotes": 99.0
  },
  {
    "type": "Brilliant",
    "unit": "UNDEAD",
    "title": "Gate of Abyss",
    "totalNotes": 132,
    "duration": "2:29",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/FXtZNEwGTNM?si=B1FQOqAc1My09wi8",
    "predicted": 72.0,
    "clearNotes": 82.0
  },
  {
    "type": "Glitter",
    "unit": "UNDEAD",
    "title": "DESTRUCTION ROAD",
    "totalNotes": 119,
    "duration": "2:22",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/AEadVvbIDTs?si=7EB3HtgDU2T4aXPM",
    "predicted": 65.0,
    "clearNotes": 75.0
  },
  {
    "type": "Brilliant",
    "unit": "UNDEAD",
    "title": "IMMORAL WORLD",
    "totalNotes": 126,
    "duration": "1:57",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/5ibK0HTyCqE",
    "predicted": 69.0,
    "clearNotes": 79.0
  },
  {
    "type": "Sparkle",
    "unit": "UNDEAD",
    "title": "PERFECTLY-IMPERFECT",
    "totalNotes": 193,
    "duration": "2:35",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/XpS8WT--GMA?si=WC61RpYpJ5Md186S",
    "predicted": 105.0,
    "clearNotes": 115.0
  },
  {
    "type": "Flash",
    "unit": "UNDEAD",
    "title": "허니밀크",
    "totalNotes": 154,
    "duration": "2:39",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/e2zo1oC_ouE?si=pXVOHxaCM-T51DyL",
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Flash",
    "unit": "UNDEAD",
    "title": "죄의 밑바닥 (罪の底)",
    "totalNotes": 184,
    "duration": "2:54",
    "etStart": 79,
    "etEnd": 111,
    "measured": 106,
    "category": "rhythm_link",
    "video": "https://youtu.be/VfIUZw1CkrE?si=qarf0WyZqsIVIcar",
    "predicted": 99.0,
    "clearNotes": 109.0
  },
  {
    "type": "Brilliant",
    "unit": "UNDEAD",
    "title": "Savage Love Affair",
    "totalNotes": 172,
    "duration": "2:26",
    "etStart": 56,
    "etEnd": 105,
    "measured": 98,
    "category": "rhythm_link",
    "video": "https://youtu.be/VjQw-7CczQY?si=fAWVQfIi3NFds-hw",
    "predicted": 93.0,
    "clearNotes": 103.0
  },
  {
    "type": "Brilliant",
    "unit": "UNDEAD",
    "title": "Darkness 4",
    "totalNotes": 106,
    "duration": "2:05",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": "https://youtu.be/f1QLJm01eJg?si=xWj4yhalHluzvXnU",
    "predicted": 58.0,
    "clearNotes": 68.0
  },
  {
    "type": "Sparkle",
    "unit": "UNDEAD",
    "title": "Nightless World",
    "totalNotes": 111,
    "duration": "2:04",
    "etStart": 57,
    "etEnd": 80,
    "measured": 57,
    "category": "rhythm_link",
    "video": "https://youtu.be/U9qxWETQMDE?si=7Tu0qSDB0-I-rI26",
    "predicted": 61.0,
    "clearNotes": 71.0
  },
  {
    "type": "Sparkle",
    "unit": "UNDEAD",
    "title": "FORBIDDEN RAIN",
    "totalNotes": 119,
    "duration": "2:15",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 65.0,
    "clearNotes": 75.0
  },
  {
    "type": "Glitter",
    "unit": "UNDEAD",
    "title": "Sustain Memories",
    "totalNotes": 137,
    "duration": "2:48",
    "etStart": 31,
    "etEnd": 58,
    "measured": 71,
    "category": "rhythm_link",
    "video": "https://youtu.be/7U1RsunFOc8?si=l9aqJXkrTgCHCE57",
    "predicted": 73.0,
    "clearNotes": 83.0
  },
  {
    "type": "Glitter",
    "unit": "UNDEAD",
    "title": "Resurrection of Soul",
    "totalNotes": 201,
    "duration": "2:46",
    "etStart": 119,
    "etEnd": 175,
    "measured": 108,
    "category": "rhythm_link",
    "video": "https://youtu.be/2QRK5t-U_F0?si=11m1UzWIRi4isplT",
    "predicted": 111.0,
    "clearNotes": 121.0
  },
  {
    "type": "Sparkle",
    "unit": "UNDEAD",
    "title": "SWINGIN' PARONIRIA",
    "totalNotes": 160,
    "duration": "2:28",
    "etStart": 114,
    "etEnd": 151,
    "measured": 85,
    "category": "rhythm_link",
    "video": "https://youtu.be/u21aGJ2glLs?si=-Y2tKw3cwpKPAczL",
    "predicted": 89.0,
    "clearNotes": 99.0
  },
  {
    "type": "Flash",
    "unit": "UNDEAD",
    "title": "Wanderlust Sailing",
    "totalNotes": 208,
    "duration": "2:25",
    "etStart": 125,
    "etEnd": 163,
    "measured": 114,
    "category": "rhythm_link",
    "video": "https://youtu.be/kkncT21bzKo?si=13QU37Tcg7dQd-RE",
    "predicted": 113.0,
    "clearNotes": 123.0
  },
  {
    "type": "Brilliant",
    "unit": "Ra*bits",
    "title": "Joyful X Box*",
    "totalNotes": 100,
    "duration": "2:28",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 55.0,
    "clearNotes": 65.0
  },
  {
    "type": "Flash",
    "unit": "Ra*bits",
    "title": "Love Ra*bits Party!!",
    "totalNotes": 140,
    "duration": "2:27",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 76.0,
    "clearNotes": 86.0
  },
  {
    "type": "Sparkle",
    "unit": "Ra*bits",
    "title": "멜티 키친",
    "totalNotes": 142,
    "duration": "2:23",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Glitter",
    "unit": "Ra*bits",
    "title": "Milky Starry Charm",
    "totalNotes": 142,
    "duration": "2:29",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Brilliant",
    "unit": "Ra*bits",
    "title": "주머니속 우주",
    "totalNotes": 128,
    "duration": "2:37",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Glitter",
    "unit": "Ra*bits",
    "title": "메이드인 도키메키",
    "totalNotes": 161,
    "duration": "2:29",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 87.0,
    "clearNotes": 97.0
  },
  {
    "type": "Sparkle",
    "unit": "Ra*bits",
    "title": "산토끼 행진곡",
    "totalNotes": 125,
    "duration": "2:16",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 68.0,
    "clearNotes": 78.0
  },
  {
    "type": "Brilliant",
    "unit": "Ra*bits",
    "title": "히카리 스펙트럼(ヒカリスペクトル)",
    "totalNotes": 163,
    "duration": "2:55",
    "etStart": 133,
    "etEnd": 152,
    "measured": 93,
    "category": "rhythm_link",
    "video": "https://youtu.be/4TBnL26Tv6c?si=ASXdvkO7M4yv_rWD",
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Sparkle",
    "unit": "Ra*bits",
    "title": "토끼 숲 음악회",
    "totalNotes": 159,
    "duration": "2:38",
    "etStart": 28,
    "etEnd": 53,
    "measured": 89,
    "category": "rhythm_link",
    "video": "https://youtu.be/D6X5kz65g6g?si=YmzByWmUP_MqsUdN",
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Brilliant",
    "unit": "Ra*bits",
    "title": "Dream Collection",
    "totalNotes": 112,
    "duration": "2:11",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 61.0,
    "clearNotes": 71.0
  },
  {
    "type": "Flash",
    "unit": "Ra*bits",
    "title": "Love it Love it",
    "totalNotes": 165,
    "duration": "2:43",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Flash",
    "unit": "Ra*bits",
    "title": "FALLIN' LOVE=IT'S WONDERLAND",
    "totalNotes": 190,
    "duration": "2:41",
    "etStart": 114,
    "etEnd": 144,
    "measured": 106,
    "category": "rhythm_link",
    "video": "https://youtu.be/C4CCRKRYMT0?si=9y4q4Y30JaTguMW6",
    "predicted": 104.0,
    "clearNotes": 114.0
  },
  {
    "type": "Sparkle",
    "unit": "Ra*bits",
    "title": "하레노히Sugar Wave",
    "totalNotes": 160,
    "duration": "2:33",
    "etStart": 58,
    "etEnd": 106,
    "measured": 88,
    "category": "rhythm_link",
    "video": "https://youtu.be/x0EDfvN_BSk?si=_LyBPi_2gLvZgyHJ",
    "predicted": 87.0,
    "clearNotes": 97.0
  },
  {
    "type": "Glitter",
    "unit": "Ra*bits",
    "title": "토모야 클막",
    "totalNotes": 170,
    "duration": "2:43",
    "etStart": 42,
    "etEnd": 58,
    "measured": 90,
    "category": "rhythm_link",
    "video": "https://youtu.be/uZfLdLld0YM",
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Brilliant",
    "unit": "Ra*bits",
    "title": "JUMPIN' LUCK BEAT",
    "totalNotes": 214,
    "duration": "2:42",
    "etStart": 81,
    "etEnd": 151,
    "measured": 126,
    "category": "rhythm_link",
    "video": "https://youtu.be/jpr4ob5gjfA?si=dPY8ei2TGtRMquao",
    "predicted": 117.0,
    "clearNotes": 127.0
  },
  {
    "type": "Brilliant",
    "unit": "Ra*bits",
    "title": "RaRaRa*Station!",
    "totalNotes": 189,
    "duration": "2:55",
    "etStart": 126,
    "etEnd": 156,
    "measured": 106,
    "category": "rhythm_link",
    "video": "https://youtu.be/R7FmVIDgs_w",
    "predicted": 103.0,
    "clearNotes": 113.0
  },
  {
    "type": "Brilliant",
    "unit": "홍월",
    "title": "백화요란 홍월야",
    "totalNotes": 200,
    "duration": "2:23",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 108.0,
    "clearNotes": 118.0
  },
  {
    "type": "Flash",
    "unit": "홍월",
    "title": "연홍빛 약속",
    "totalNotes": 133,
    "duration": "2:30",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 72.0,
    "clearNotes": 82.0
  },
  {
    "type": "Glitter",
    "unit": "홍월",
    "title": "무슨 검",
    "totalNotes": 136,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 74.0,
    "clearNotes": 84.0
  },
  {
    "type": "Sparkle",
    "unit": "홍월",
    "title": "제야회권",
    "totalNotes": 167,
    "duration": "2:23",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 91.0,
    "clearNotes": 101.0
  },
  {
    "type": "Flash",
    "unit": "홍월",
    "title": "월화무쌍 붉은춤(月下無双、紅の舞)",
    "totalNotes": 190,
    "duration": "2:35",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 103.0,
    "clearNotes": 113.0
  },
  {
    "type": "Brilliant",
    "unit": "홍월",
    "title": "무슨 춤",
    "totalNotes": 144,
    "duration": "2:21",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 78.0,
    "clearNotes": 88.0
  },
  {
    "type": "Flash",
    "unit": "홍월",
    "title": "실",
    "totalNotes": 168,
    "duration": "2:52",
    "etStart": 64,
    "etEnd": 93,
    "measured": 89,
    "category": "rhythm_link",
    "video": "https://youtu.be/11C7MwwRWMw?si=eP8rjwufD6VBbDat",
    "predicted": 91.0,
    "clearNotes": 101.0
  },
  {
    "type": "Brilliant",
    "unit": "홍월",
    "title": "밤까치",
    "totalNotes": 114,
    "duration": "2:18",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 62.0,
    "clearNotes": 72.0
  },
  {
    "type": "Brilliant",
    "unit": "홍월",
    "title": "백화요란 2025",
    "totalNotes": 206,
    "duration": "2:35",
    "etStart": 117,
    "etEnd": 147,
    "measured": 117,
    "category": "rhythm_link",
    "video": "https://youtu.be/lqf2x1GKkVg?si=rLLmjwR7Etv-CCk0",
    "predicted": 112.0,
    "clearNotes": 122.0
  },
  {
    "type": "Sparkle",
    "unit": "홍월",
    "title": "발키리 커버",
    "totalNotes": 155,
    "duration": "2:49",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Glitter",
    "unit": "홍월",
    "title": "홍월 이로하",
    "totalNotes": 168,
    "duration": "2:08",
    "etStart": 119,
    "etEnd": 130,
    "measured": 95,
    "category": "rhythm_link",
    "video": "https://youtu.be/TE9kO9CtHZY?si=LH0kVRGBhb1fCYtf",
    "predicted": 92.0,
    "clearNotes": 102.0
  },
  {
    "type": "Glitter",
    "unit": "홍월",
    "title": "월광기담",
    "totalNotes": 155,
    "duration": "2:43",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Glitter",
    "unit": "홍월",
    "title": "써머버드",
    "totalNotes": 141,
    "duration": "2:40",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Sparkle",
    "unit": "홍월",
    "title": "금색천야",
    "totalNotes": 217,
    "duration": "2:46",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "rhythm_link",
    "video": null,
    "predicted": 117.0,
    "clearNotes": 127.0
  },
  {
    "type": "Sparkle",
    "unit": "홍월",
    "title": "천상KAGETSU",
    "totalNotes": 198,
    "duration": "2:53",
    "etStart": 55,
    "etEnd": 105,
    "measured": 106,
    "category": "rhythm_link",
    "video": "https://youtu.be/iI7IE1ZbDUg?si=N3jxe0eHlE8JPqwL",
    "predicted": 107.0,
    "clearNotes": 117.0
  },
  {
    "type": "Glitter",
    "unit": "홍월",
    "title": "LOUDEST BUGS",
    "totalNotes": 222,
    "duration": "2:31",
    "etStart": 78,
    "etEnd": 104,
    "measured": 115,
    "category": "rhythm_link",
    "video": "https://youtu.be/mqMkkKZJDSA?si=ETeu8rR1mFg0JRLj",
    "predicted": 119.0,
    "clearNotes": 129.0
  },
  {
    "type": "Sparkle",
    "unit": "멜로디",
    "title": "Dear World 마피",
    "totalNotes": 180,
    "duration": "2:29",
    "etStart": 0,
    "etEnd": 0,
    "measured": 102,
    "category": "rhythm_link",
    "video": "https://youtu.be/6OgHDJn3iPE?si=MThi_08vZH1ffs7q",
    "predicted": 98.0,
    "clearNotes": 108.0
  },
  {
    "type": "Sparkle",
    "unit": "멜로디",
    "title": "Dear World",
    "totalNotes": 158,
    "duration": "2:41",
    "etStart": 82,
    "etEnd": 105,
    "measured": 87,
    "category": "rhythm_link",
    "video": "https://youtu.be/VPpQsQ4DYF4?si=ilsluz4VPIhgCK5E",
    "predicted": 86.0,
    "clearNotes": 96.0
  },
  {
    "type": "Flash",
    "unit": "멜로디",
    "title": "BUBBLE GUM DANCE",
    "totalNotes": 153,
    "duration": "2:29",
    "etStart": 58,
    "etEnd": 72,
    "measured": 84,
    "category": "rhythm_link",
    "video": "https://youtu.be/-9ozN9GEx4I?si=EgQ4ceHvqMFK-RiA",
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Sparkle",
    "unit": "홍월",
    "title": "염전염용 천변만화(炎纏焰踊千変万火)",
    "totalNotes": 208,
    "duration": "2:45",
    "etStart": 1,
    "etEnd": 13,
    "measured": 110,
    "category": "rhythm_link",
    "video": "https://youtu.be/-gtAqdLXUnA?si=usSk2BkRptKbsvGo",
    "predicted": 108.0,
    "clearNotes": 118.0
  },
  {
    "type": "Glitter",
    "unit": "나이츠",
    "title": "Voice of Sword",
    "totalNotes": 135,
    "duration": "2:36",
    "etStart": 58,
    "etEnd": 84,
    "measured": 75,
    "category": "new_dimension",
    "video": "https://youtu.be/Y_dfB-rMwAI?si=dvrZtDh0k9CVKzi7",
    "predicted": 73.0,
    "clearNotes": 83.0
  },
  {
    "type": "Brilliant",
    "unit": "나이츠",
    "title": "Silent Oath",
    "totalNotes": 106,
    "duration": "2:10",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 58.0,
    "clearNotes": 68.0
  },
  {
    "type": "Sparkle",
    "unit": "나이츠",
    "title": "Grateful Allegiance",
    "totalNotes": 96,
    "duration": "2:10",
    "etStart": 62,
    "etEnd": 78,
    "measured": 53,
    "category": "new_dimension",
    "video": "https://youtu.be/Mt-aFDzGxeo?si=SsXIJ93sfdVntKuH",
    "predicted": 54.0,
    "clearNotes": 64.0
  },
  {
    "type": "Flash",
    "unit": "나이츠",
    "title": "Fight for Judge",
    "totalNotes": 159,
    "duration": "2:32",
    "etStart": 91,
    "etEnd": 110,
    "measured": 85,
    "category": "new_dimension",
    "video": "https://youtu.be/OnR5oh8N_Rw?si=lbXe3Yie2sTODL70",
    "predicted": 86.0,
    "clearNotes": 96.0
  },
  {
    "type": "Glitter",
    "unit": "나이츠",
    "title": "Promise Swords",
    "totalNotes": 172,
    "duration": "2:48",
    "etStart": 88,
    "etEnd": 105,
    "measured": 88,
    "category": "new_dimension",
    "video": "https://youtu.be/VMLQm7BKu4c?si=EcvAURc3Mpfjm99G",
    "predicted": 93.0,
    "clearNotes": 103.0
  },
  {
    "type": "Brilliant",
    "unit": "나이츠",
    "title": "Article of Faith",
    "totalNotes": 144,
    "duration": "2:26",
    "etStart": 106,
    "etEnd": 137,
    "measured": 80,
    "category": "new_dimension",
    "video": "https://youtu.be/bljn1rmENg0?si=PLuOYXy1R_irARCe",
    "predicted": 80.0,
    "clearNotes": 90.0
  },
  {
    "type": "Flash",
    "unit": "나이츠",
    "title": "Wonderful Happiness",
    "totalNotes": 175,
    "duration": "2:49",
    "etStart": 55,
    "etEnd": 114,
    "measured": 96,
    "category": "new_dimension",
    "video": "https://youtu.be/Kgi-GfMs9dc",
    "predicted": 96.0,
    "clearNotes": 106.0
  },
  {
    "type": "Glitter",
    "unit": "나이츠",
    "title": "Castle of my Heart",
    "totalNotes": 159,
    "duration": "2:51",
    "etStart": 1,
    "etEnd": 6,
    "measured": 89,
    "category": "new_dimension",
    "video": "https://youtu.be/oZB7A0CkQt8?si=DYp4d7xGgDZD8KAP",
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Sparkle",
    "unit": "나이츠",
    "title": "Knights the Phantom Thief 나팬싶",
    "totalNotes": 116,
    "duration": "2:24",
    "etStart": 80,
    "etEnd": 96,
    "measured": 67,
    "category": "new_dimension",
    "video": "https://youtu.be/IPTEOEH7LcE?si=hDLlPj-ILaqI-6Bk",
    "predicted": 64.0,
    "clearNotes": 74.0
  },
  {
    "type": "Sparkle",
    "unit": "나이츠",
    "title": "Little Romance",
    "totalNotes": 137,
    "duration": "2:41",
    "etStart": 97,
    "etEnd": 115,
    "measured": 71,
    "category": "new_dimension",
    "video": "https://youtu.be/hXvSF8dbEfk?si=LGwVnyJ2wOzUTql0",
    "predicted": 76.0,
    "clearNotes": 86.0
  },
  {
    "type": "Flash",
    "unit": "나이츠",
    "title": "Mystic Fragrance",
    "totalNotes": 145,
    "duration": "2:20",
    "etStart": 93,
    "etEnd": 130,
    "measured": 83,
    "category": "new_dimension",
    "video": "https://youtu.be/6Q0cZ3sxJaQ?si=croDhuyG7Jrs-4jd",
    "predicted": 81.0,
    "clearNotes": 91.0
  },
  {
    "type": "Glitter",
    "unit": "나이츠",
    "title": "Coruscate Breeze",
    "totalNotes": 142,
    "duration": "2:49",
    "etStart": 104,
    "etEnd": 119,
    "measured": 79,
    "category": "new_dimension",
    "video": "https://youtu.be/W_hPeGRVwdY?si=ORyljHeY0ax9uoEC",
    "predicted": 78.0,
    "clearNotes": 88.0
  },
  {
    "type": "Brilliant",
    "unit": "나이츠",
    "title": "Or the Beautiful Golden Drop",
    "totalNotes": 189,
    "duration": "2:56",
    "etStart": 69,
    "etEnd": 89,
    "measured": 100,
    "category": "new_dimension",
    "video": "https://youtu.be/tNKnEgJ60P0?si=i6DT4rRIRsZ1pGlW",
    "predicted": 101.0,
    "clearNotes": 111.0
  },
  {
    "type": "Brilliant",
    "unit": "나이츠",
    "title": "Luminous Crown",
    "totalNotes": 141,
    "duration": "2:40",
    "etStart": 48,
    "etEnd": 68,
    "measured": 74,
    "category": "new_dimension",
    "video": "https://youtu.be/yB08ylHfQng?si=pZFwY2RRnCM2OYuT",
    "predicted": 76.0,
    "clearNotes": 86.0
  },
  {
    "type": "Brilliant",
    "unit": "나이츠",
    "title": "Heart Collector",
    "totalNotes": 164,
    "duration": "2:54",
    "etStart": 107,
    "etEnd": 131,
    "measured": 93,
    "category": "new_dimension",
    "video": "https://youtu.be/-xnmtYualr4?si=SEqJGkWSPzQjE0l9",
    "predicted": 90.0,
    "clearNotes": 100.0
  },
  {
    "type": "Sparkle",
    "unit": "스위치",
    "title": "템테 매직",
    "totalNotes": 103,
    "duration": "2:17",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 56.0,
    "clearNotes": 66.0
  },
  {
    "type": "Brilliant",
    "unit": "스위치",
    "title": "에메랄드 플래닛",
    "totalNotes": 143,
    "duration": "2:29",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 78.0,
    "clearNotes": 88.0
  },
  {
    "type": "Flash",
    "unit": "스위치",
    "title": "노킹 판타지",
    "totalNotes": 106,
    "duration": "2:15",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 58.0,
    "clearNotes": 68.0
  },
  {
    "type": "Glitter",
    "unit": "스위치",
    "title": "I ”Witch” You A Happy Halloween! 할로윈 ",
    "totalNotes": 145,
    "duration": "2:28",
    "etStart": 103,
    "etEnd": 135,
    "measured": 80,
    "category": "new_dimension",
    "video": "https://youtu.be/F6Y2z7BtlBM?si=jABXQDsbLDHz2_-v",
    "predicted": 81.0,
    "clearNotes": 91.0
  },
  {
    "type": "Glitter",
    "unit": "스위치",
    "title": "매직 포 유어 스위치",
    "totalNotes": 178,
    "duration": "2:36",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 97.0,
    "clearNotes": 107.0
  },
  {
    "type": "Flash",
    "unit": "스위치",
    "title": "갤럭시 데스티니",
    "totalNotes": 103,
    "duration": "2:13",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 56.0,
    "clearNotes": 66.0
  },
  {
    "type": "Glitter",
    "unit": "스위치",
    "title": "Seven Days \"Prismagic\" (스위치 트립)",
    "totalNotes": 143,
    "duration": "2:47",
    "etStart": 115,
    "etEnd": 139,
    "measured": 75,
    "category": "new_dimension",
    "video": "https://youtu.be/g9Pp5b45YCo?si=ivNyZPn8r7he9S0A",
    "predicted": 80.0,
    "clearNotes": 90.0
  },
  {
    "type": "Flash",
    "unit": "스위치",
    "title": "이스터 카니발",
    "totalNotes": 198,
    "duration": "2:33",
    "etStart": 62,
    "etEnd": 98,
    "measured": 104,
    "category": "new_dimension",
    "video": "https://youtu.be/qw0zoJpOqQw?si=vYztjSdMyfWE3WAV",
    "predicted": 106.0,
    "clearNotes": 116.0
  },
  {
    "type": "Flash",
    "unit": "스위치",
    "title": "A little bit UP!!",
    "totalNotes": 135,
    "duration": "2:46",
    "etStart": 108,
    "etEnd": 118,
    "measured": 74,
    "category": "new_dimension",
    "video": "https://youtu.be/QiE_mrDMqbk?si=zhN9g92tTnNMDUep",
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Brilliant",
    "unit": "스위치",
    "title": "오모카게",
    "totalNotes": 130,
    "duration": "1:58",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 71.0,
    "clearNotes": 81.0
  },
  {
    "type": "Brilliant",
    "unit": "스위치",
    "title": "Brilliant Smile",
    "totalNotes": 198,
    "duration": "2:44",
    "etStart": 151,
    "etEnd": 169,
    "measured": 105,
    "category": "new_dimension",
    "video": "https://youtu.be/yeuMMCHFfUA?si=bIUqgaAyNBLXOb-C",
    "predicted": 108.0,
    "clearNotes": 118.0
  },
  {
    "type": "Sparkle",
    "unit": "스위치",
    "title": "로맨싱 크루즈",
    "totalNotes": 148,
    "duration": "2:36",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 81.0,
    "clearNotes": 91.0
  },
  {
    "type": "Sparkle",
    "unit": "스위치",
    "title": "Chocola-Tic After School 스위치 발렌",
    "totalNotes": 142,
    "duration": "2:47",
    "etStart": 101,
    "etEnd": 117,
    "measured": 80,
    "category": "new_dimension",
    "video": "https://youtu.be/maUqiZk7sCk?si=eaLE2Dma927sP_Sy",
    "predicted": 78.0,
    "clearNotes": 88.0
  },
  {
    "type": "Flash",
    "unit": "스위치",
    "title": "Wish upon a MUSIC!!",
    "totalNotes": 142,
    "duration": "2:51",
    "etStart": 35,
    "etEnd": 58,
    "measured": 72,
    "category": "new_dimension",
    "video": "https://youtu.be/7WzOUpKOHtI?si=gtdElgxFjN0TkBHj",
    "predicted": 76.0,
    "clearNotes": 86.0
  },
  {
    "type": "Glitter",
    "unit": "스위치",
    "title": "Switching Journey",
    "totalNotes": 146,
    "duration": "2:41",
    "etStart": 122,
    "etEnd": 133,
    "measured": 86,
    "category": "new_dimension",
    "video": "https://youtu.be/xafCUkCr94I?si=d85wmfxusbd-YBSd",
    "predicted": 81.0,
    "clearNotes": 91.0
  },
  {
    "type": "Glitter",
    "unit": "마무",
    "title": "블루밍",
    "totalNotes": 141,
    "duration": "2:11",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": "https://youtu.be/1engaOH1-EA?si=1nJ3XCmxsp8yf9Ww",
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Sparkle",
    "unit": "마무",
    "title": "엠비셔스",
    "totalNotes": 131,
    "duration": "2:11",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": "https://youtu.be/M2SlMp8nDF0?si=JTTzVUSHWF3vwA3S",
    "predicted": 71.0,
    "clearNotes": 81.0
  },
  {
    "type": "Brilliant",
    "unit": "마무",
    "title": "페스티브",
    "totalNotes": 121,
    "duration": "2:13",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 66.0,
    "clearNotes": 76.0
  },
  {
    "type": "Flash",
    "unit": "마무",
    "title": "유쾌통쾌 That's alright! 다라닥닥",
    "totalNotes": 202,
    "duration": "2:32",
    "etStart": 124,
    "etEnd": 143,
    "measured": 103,
    "category": "new_dimension",
    "video": "https://youtu.be/XJA4yTIcSi8?si=ZvPsX922n-R_dMu7",
    "predicted": 109.0,
    "clearNotes": 119.0
  },
  {
    "type": "Brilliant",
    "unit": "마무",
    "title": "신풍",
    "totalNotes": 141,
    "duration": "2:28",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Flash",
    "unit": "마무",
    "title": "핸즈크레프트",
    "totalNotes": 121,
    "duration": "2:45",
    "etStart": 62,
    "etEnd": 72,
    "measured": 62,
    "category": "new_dimension",
    "video": "https://youtu.be/wU4xQ9hyhcA?si=nrPSlUDVggN3HZL6",
    "predicted": 65.0,
    "clearNotes": 75.0
  },
  {
    "type": "Glitter",
    "unit": "마무",
    "title": "헬로 뉴이어",
    "totalNotes": 101,
    "duration": "2:48",
    "etStart": 57,
    "etEnd": 72,
    "measured": 57,
    "category": "new_dimension",
    "video": "https://youtu.be/XqU_u7YF_4k?si=DT0ibUjxmDgR-hQf",
    "predicted": 56.0,
    "clearNotes": 66.0
  },
  {
    "type": "Brilliant",
    "unit": "마무",
    "title": "할로윈 랑데부",
    "totalNotes": 181,
    "duration": "2:51",
    "etStart": 119,
    "etEnd": 151,
    "measured": 98,
    "category": "new_dimension",
    "video": "https://youtu.be/ypuz0XTP_Yw?si=-bc4zHdJ3OHuzBtG",
    "predicted": 99.0,
    "clearNotes": 109.0
  },
  {
    "type": "Flash",
    "unit": "덥페",
    "title": "Stippling",
    "totalNotes": 132,
    "duration": "2:14",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 72.0,
    "clearNotes": 82.0
  },
  {
    "type": "Brilliant",
    "unit": "덥페",
    "title": "주머니 속 우주",
    "totalNotes": 128,
    "duration": "2:37",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "new_dimension",
    "video": null,
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Glitter",
    "unit": "덥페",
    "title": "네뷸라",
    "totalNotes": 160,
    "duration": "2:46",
    "etStart": 58,
    "etEnd": 84,
    "measured": 85,
    "category": "new_dimension",
    "video": "https://youtu.be/nvW4Sb5j_os?si=EHgZ9zRV5LBZ163p",
    "predicted": 86.0,
    "clearNotes": 96.0
  },
  {
    "type": "Sparkle",
    "unit": "덥페",
    "title": "=아이=",
    "totalNotes": 151,
    "duration": "2:26",
    "etStart": 55,
    "etEnd": 96,
    "measured": 84,
    "category": "new_dimension",
    "video": "https://youtu.be/5W8iksoImZ0?si=RadE3upquKGY4kBb",
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Brilliant",
    "unit": "덥페",
    "title": "No name yet",
    "totalNotes": 147,
    "duration": "2:32",
    "etStart": 96,
    "etEnd": 110,
    "measured": 85,
    "category": "new_dimension",
    "video": "https://youtu.be/1fxv7EJyDrQ?si=o917z-_sV068A4e8",
    "predicted": 80.0,
    "clearNotes": 90.0
  },
  {
    "type": "Brilliant",
    "unit": "덥페",
    "title": "바이바이 버디",
    "totalNotes": 194,
    "duration": "2:43",
    "etStart": 148,
    "etEnd": 165,
    "measured": 112,
    "category": "new_dimension",
    "video": "https://youtu.be/igayZQFSmGY?si=fNzUBk-sJJ79XuMA",
    "predicted": 106.0,
    "clearNotes": 116.0
  },
  {
    "type": "Flash",
    "unit": "에스프리",
    "title": "상애선언",
    "totalNotes": 211,
    "duration": "2:56",
    "etStart": 36,
    "etEnd": 50,
    "measured": 111,
    "category": "new_dimension",
    "video": "https://youtu.be/LejZx0toLQc?si=b_Xe4v94YcifbF2R",
    "predicted": 111.0,
    "clearNotes": 121.0
  },
  {
    "type": "Glitter",
    "unit": "에스프리",
    "title": "스키스키 헌터",
    "totalNotes": 201,
    "duration": "2:43",
    "etStart": 125,
    "etEnd": 141,
    "measured": 104,
    "category": "new_dimension",
    "video": "https://youtu.be/LXhAtH7jCJU?si=oBePbPTzIGawjaek",
    "predicted": 109.0,
    "clearNotes": 119.0
  },
  {
    "type": "Sparkle",
    "unit": "에스프리",
    "title": "Be My Princess 비마프",
    "totalNotes": 193,
    "duration": "2:47",
    "etStart": 140,
    "etEnd": 157,
    "measured": 107,
    "category": "new_dimension",
    "video": "https://youtu.be/3kSEGCzfomw?si=3YJt9cUK8qg9D5xP",
    "predicted": 105.0,
    "clearNotes": 115.0
  },
  {
    "type": "Glitter",
    "unit": "에스프리",
    "title": "베리베리 스위트 화이트",
    "totalNotes": 149,
    "duration": "2:13",
    "etStart": 105,
    "etEnd": 122,
    "measured": 83,
    "category": "new_dimension",
    "video": "https://youtu.be/tk7kSTGCa5A?si=EvjRSwA-spA-_bzv",
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Glitter",
    "unit": "에스프리",
    "title": "칸나 하코",
    "totalNotes": 166,
    "duration": "2:33",
    "etStart": 121,
    "etEnd": 132,
    "measured": 90,
    "category": "new_dimension",
    "video": "https://youtu.be/e4JWzY_Iki4?si=wYLh8wMhGAsWHKOA",
    "predicted": 91.0,
    "clearNotes": 101.0
  },
  {
    "type": "Glitter",
    "unit": "마무",
    "title": "Light on the Orbit 감사제",
    "totalNotes": 131,
    "duration": "2:41",
    "etStart": 85,
    "etEnd": 119,
    "measured": 73,
    "category": "new_dimension",
    "video": "https://youtu.be/swjbhhjcaIw?si=pTMzetSaGciJYK56",
    "predicted": 73.0,
    "clearNotes": 83.0
  },
  {
    "type": "Brilliant",
    "unit": "나이츠",
    "title": "시크릿 마스커레이드",
    "totalNotes": 183,
    "duration": "2:41",
    "etStart": 97,
    "etEnd": 107,
    "measured": 99,
    "category": "new_dimension",
    "video": "https://youtu.be/4HxEhn3UljA",
    "predicted": 98.0,
    "clearNotes": 108.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "BRAND NEW STARS!! 브뉴스",
    "totalNotes": 118,
    "duration": "2:08",
    "etStart": 68,
    "etEnd": 94,
    "measured": 68,
    "category": "others",
    "video": "https://youtu.be/7g4vefHWPvc?si=LivgcBOApU2IiUuq",
    "predicted": 66.0,
    "clearNotes": 76.0
  },
  {
    "type": "All",
    "unit": "기타",
    "title": "스타즈 앙상블",
    "totalNotes": 80,
    "duration": "2:39",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 44.0,
    "clearNotes": 54.0
  },
  {
    "type": "Brilliant",
    "unit": "진앤아",
    "title": "Rainbow Stairway",
    "totalNotes": 121,
    "duration": "2:25",
    "etStart": 41,
    "etEnd": 69,
    "measured": 61,
    "category": "others",
    "video": "https://youtu.be/5eGMuT05V34?si=vDXVzhUiJnl-Oic2",
    "predicted": 66.0,
    "clearNotes": 76.0
  },
  {
    "type": "Sparkle",
    "unit": "추억",
    "title": "익센파",
    "totalNotes": 127,
    "duration": "2:28",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 69.0,
    "clearNotes": 79.0
  },
  {
    "type": "Flash",
    "unit": "추억",
    "title": "제뉴인",
    "totalNotes": 123,
    "duration": "2:13",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 67.0,
    "clearNotes": 77.0
  },
  {
    "type": "Brilliant",
    "unit": "추억",
    "title": "데겜홀",
    "totalNotes": 235,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 127.0,
    "clearNotes": 137.0
  },
  {
    "type": "Glitter",
    "unit": "추억",
    "title": "Crush of Judgment 나킬",
    "totalNotes": 154,
    "duration": "2:24",
    "etStart": 65,
    "etEnd": 96,
    "measured": 87,
    "category": "others",
    "video": "https://youtu.be/v6xB4TsnL1k?si=4HFlYuhsvrr4dC-o",
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Sparkle",
    "unit": "추억",
    "title": "락 로어",
    "totalNotes": 208,
    "duration": "2:40",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 113.0,
    "clearNotes": 123.0
  },
  {
    "type": "Sparkle",
    "unit": "추억",
    "title": "We'll be knights 윌비나",
    "totalNotes": 99,
    "duration": "2:19",
    "etStart": 67,
    "etEnd": 93,
    "measured": 59,
    "category": "others",
    "video": "https://youtu.be/BZdA8fqqojc?si=017TRTtHsKgxz6x0",
    "predicted": 56.0,
    "clearNotes": 66.0
  },
  {
    "type": "Sparkle",
    "unit": "추억",
    "title": "성소년유희",
    "totalNotes": 160,
    "duration": "2:20",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 87.0,
    "clearNotes": 97.0
  },
  {
    "type": "Sparkle",
    "unit": "드림유닛",
    "title": "반짝 Sign",
    "totalNotes": 179,
    "duration": "2:46",
    "etStart": 119,
    "etEnd": 150,
    "measured": 96,
    "category": "others",
    "video": "https://youtu.be/V-kfyMIHYQw?si=dNTAJpxaa9dlLF0J",
    "predicted": 98.0,
    "clearNotes": 108.0
  },
  {
    "type": "Brilliant",
    "unit": "드림유닛",
    "title": "세츠나 Drops",
    "totalNotes": 91,
    "duration": "2:32",
    "etStart": 53,
    "etEnd": 82,
    "measured": 53,
    "category": "others",
    "video": "https://youtu.be/Dy_Urf3pbwo?si=m1LYuI1XcJdOBMmW",
    "predicted": 52.0,
    "clearNotes": 62.0
  },
  {
    "type": "Brilliant",
    "unit": "드림유닛",
    "title": "LOCK YOUR GAZE",
    "totalNotes": 157,
    "duration": "2:09",
    "etStart": 35,
    "etEnd": 62,
    "measured": 77,
    "category": "others",
    "video": "https://youtu.be/p7d6v93yPVc",
    "predicted": 84.0,
    "clearNotes": 94.0
  },
  {
    "type": "Sparkle",
    "unit": "만우절",
    "title": "앙상블 체조",
    "totalNotes": 176,
    "duration": "2:51",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 96.0,
    "clearNotes": 106.0
  },
  {
    "type": "Glitter",
    "unit": "셔플",
    "title": "에투제",
    "totalNotes": 151,
    "duration": "2:30",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "웤유스",
    "totalNotes": 103,
    "duration": "2:00",
    "etStart": 57,
    "etEnd": 82,
    "measured": 57,
    "category": "others",
    "video": "https://youtu.be/WbBI2QjyTrk?si=HXwT_0D2eFAChgc_",
    "predicted": 58.0,
    "clearNotes": 68.0
  },
  {
    "type": "Brilliant",
    "unit": "셔플",
    "title": "버틀러",
    "totalNotes": 141,
    "duration": "2:05",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Glitter",
    "unit": "셔플",
    "title": "블랑코",
    "totalNotes": 98,
    "duration": "2:09",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 54.0,
    "clearNotes": 64.0
  },
  {
    "type": "All",
    "unit": "새해",
    "title": "2020 -> 2021",
    "totalNotes": 210,
    "duration": "3:19",
    "etStart": 100,
    "etEnd": 117,
    "measured": 109,
    "category": "others",
    "video": "https://youtu.be/RqGC-mI6A8k?si=CT-UaETRgT9WQEZU",
    "predicted": 113.0,
    "clearNotes": 123.0
  },
  {
    "type": "Sparkle",
    "unit": "만우절",
    "title": "엔드리스 뷔데",
    "totalNotes": 132,
    "duration": "2:31",
    "etStart": 0,
    "etEnd": 0,
    "measured": 67,
    "category": "others",
    "video": "https://youtu.be/1NfFzQ6ipzA?si=qp2-tsTyzkyuAQc7",
    "predicted": 72.0,
    "clearNotes": 82.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "웤유스 어쿠스틱 (Acoustic Ver.)",
    "totalNotes": 167,
    "duration": "3:04",
    "etStart": 0,
    "etEnd": 0,
    "measured": 89,
    "category": "others",
    "video": "https://youtu.be/kPruu3fcEZI?si=aLbN4tkSZLsuwiuZ",
    "predicted": 91.0,
    "clearNotes": 101.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "6주년 퓨저닉",
    "totalNotes": 214,
    "duration": "2:46",
    "etStart": 111,
    "etEnd": 145,
    "measured": 111,
    "category": "others",
    "video": "https://youtu.be/2MkdWOiUKpQ?si=QlnzDnryT0IQN5Uq",
    "predicted": 116.0,
    "clearNotes": 126.0
  },
  {
    "type": "Brilliant",
    "unit": "셔플",
    "title": "링어벨",
    "totalNotes": 169,
    "duration": "2:39",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 92.0,
    "clearNotes": 102.0
  },
  {
    "type": "Glitter",
    "unit": "셔플",
    "title": "문라디",
    "totalNotes": 146,
    "duration": "2:15",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 79.0,
    "clearNotes": 89.0
  },
  {
    "type": "Glitter",
    "unit": "셔플",
    "title": "Noir Neige (흑설)",
    "totalNotes": 166,
    "duration": "2:42",
    "etStart": 38,
    "etEnd": 56,
    "measured": 86,
    "category": "others",
    "video": "https://youtu.be/Um2Snuz-uy4?si=ocerjGdxYoFGCTk5",
    "predicted": 88.0,
    "clearNotes": 98.0
  },
  {
    "type": "All",
    "unit": "새해",
    "title": "2021 -> 2022",
    "totalNotes": 210,
    "duration": "3:25",
    "etStart": 135,
    "etEnd": 152,
    "measured": 103,
    "category": "others",
    "video": "https://youtu.be/uFvTZ6udsRs?si=v1IplzAPa8F8PCYE",
    "predicted": 114.0,
    "clearNotes": 124.0
  },
  {
    "type": "All",
    "unit": "기타",
    "title": "Life is so Drastic (로투쇼)",
    "totalNotes": 194,
    "duration": "2:46",
    "etStart": 0,
    "etEnd": 0,
    "measured": 100,
    "category": "others",
    "video": "https://youtu.be/tLhUaM7Y-c8?si=E8ZTd9s2Th_nqxzU",
    "predicted": 105.0,
    "clearNotes": 115.0
  },
  {
    "type": "All",
    "unit": "만우절",
    "title": "부쿠부 스타즈",
    "totalNotes": 160,
    "duration": "2:11",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 87.0,
    "clearNotes": 97.0
  },
  {
    "type": "Sparkle",
    "unit": "셔플",
    "title": "부활절 토끼",
    "totalNotes": 161,
    "duration": "2:29",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 87.0,
    "clearNotes": 97.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "Surprising Thanks!! 7주년",
    "totalNotes": 159,
    "duration": "2:28",
    "etStart": 122,
    "etEnd": 147,
    "measured": 91,
    "category": "others",
    "video": "https://youtu.be/N7I7l6fLAlE?si=slYdJjtLp6zNwFix",
    "predicted": 88.0,
    "clearNotes": 98.0
  },
  {
    "type": "Sparkle",
    "unit": "셔플",
    "title": "FIST OF SOUL",
    "totalNotes": 176,
    "duration": "2:41",
    "etStart": 137,
    "etEnd": 155,
    "measured": 104,
    "category": "others",
    "video": "https://youtu.be/wOKpdmTdyRY?si=C8lbXFln5FVuq5jz",
    "predicted": 97.0,
    "clearNotes": 107.0
  },
  {
    "type": "Sparkle",
    "unit": "셔플",
    "title": "카페테리아",
    "totalNotes": 142,
    "duration": "2:42",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 77.0,
    "clearNotes": 87.0
  },
  {
    "type": "Flash",
    "unit": "셔플",
    "title": "Have you been naughty or nice?",
    "totalNotes": 218,
    "duration": "2:24",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 118.0,
    "clearNotes": 128.0
  },
  {
    "type": "All",
    "unit": "새해",
    "title": "2022 -> 2023",
    "totalNotes": 253,
    "duration": "3:40",
    "etStart": 187,
    "etEnd": 206,
    "measured": 129,
    "category": "others",
    "video": "https://youtu.be/kNPHVS4gDNs?si=uU9tJozm-mDltkhl",
    "predicted": 137.0,
    "clearNotes": 147.0
  },
  {
    "type": "Brilliant",
    "unit": "만우절",
    "title": "앙상블 트레이닝",
    "totalNotes": 83,
    "duration": "2:51",
    "etStart": 47,
    "etEnd": 67,
    "measured": 47,
    "category": "others",
    "video": "https://youtu.be/Q3pKOW2HvdY?si=VcC52PYzQ8RiFMOy",
    "predicted": 47.0,
    "clearNotes": 57.0
  },
  {
    "type": "Glitter",
    "unit": "추억",
    "title": "익센파 Mix",
    "totalNotes": 175,
    "duration": "2:47",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 95.0,
    "clearNotes": 105.0
  },
  {
    "type": "Brilliant",
    "unit": "기타",
    "title": "Twilight Pentagram 팬타그램",
    "totalNotes": 186,
    "duration": "2:53",
    "etStart": 1,
    "etEnd": 9,
    "measured": 99,
    "category": "others",
    "video": "https://youtu.be/wf5sxYlZIAE?si=xVfs6g8MJQ__faHC",
    "predicted": 97.0,
    "clearNotes": 107.0
  },
  {
    "type": "Glitter",
    "unit": "기타",
    "title": "Dawning Angels",
    "totalNotes": 194,
    "duration": "2:49",
    "etStart": 136,
    "etEnd": 150,
    "measured": 108,
    "category": "others",
    "video": "https://youtu.be/5qLQm9m3tgc?si=YF9UwrPItDDJBVqQ",
    "predicted": 106.0,
    "clearNotes": 116.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "One with One (8주년)",
    "totalNotes": 208,
    "duration": "2:50",
    "etStart": 0,
    "etEnd": 0,
    "measured": 105,
    "category": "others",
    "video": "https://youtu.be/fywI-2pTEG4?si=CG19aekVbHlyu-oh",
    "predicted": 113.0,
    "clearNotes": 123.0
  },
  {
    "type": "All",
    "unit": "만우절",
    "title": "스크럼블 교차로",
    "totalNotes": 131,
    "duration": "2:30",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 71.0,
    "clearNotes": 81.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "LIMIT BREAK DREAMERS (9주년)",
    "totalNotes": 172,
    "duration": "2:53",
    "etStart": 58,
    "etEnd": 69,
    "measured": 89,
    "category": "others",
    "video": "https://youtu.be/YGrLwg4f8Ak?si=_pPbLBs7pjwV0Y6n",
    "predicted": 91.0,
    "clearNotes": 101.0
  },
  {
    "type": "Sparkle",
    "unit": "셔플",
    "title": "링잉 이블 폰",
    "totalNotes": 149,
    "duration": "2:50",
    "etStart": 98,
    "etEnd": 123,
    "measured": 89,
    "category": "others",
    "video": "https://youtu.be/sICZ_Yed7PQ?si=dh8SbmUDJSaNOmGu",
    "predicted": 82.0,
    "clearNotes": 92.0
  },
  {
    "type": "Brilliant",
    "unit": "셔플",
    "title": "상실우의(喪失寓意) -LOST BALLADE-",
    "totalNotes": 128,
    "duration": "2:33",
    "etStart": 25,
    "etEnd": 41,
    "measured": 69,
    "category": "others",
    "video": "https://youtu.be/XAxsfjzjYy0?si=DPqdp_7JuiPfEuJP",
    "predicted": 67.0,
    "clearNotes": 77.0
  },
  {
    "type": "All",
    "unit": "콜라보",
    "title": "We Are Light (에리오스)",
    "totalNotes": 199,
    "duration": "2:41",
    "etStart": 0,
    "etEnd": 0,
    "measured": 106,
    "category": "others",
    "video": "https://youtu.be/w1UBqwrN6X4?si=n-d_lJIwTmFNx0IK",
    "predicted": 108.0,
    "clearNotes": 118.0
  },
  {
    "type": "Flash",
    "unit": "콜라보",
    "title": "퓨전",
    "totalNotes": 174,
    "duration": "2:27",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 94.0,
    "clearNotes": 104.0
  },
  {
    "type": "Flash",
    "unit": "콜라보",
    "title": "B100d Hunter 블러드헌터",
    "totalNotes": 184,
    "duration": "2:29",
    "etStart": 0,
    "etEnd": 0,
    "measured": 98,
    "category": "others",
    "video": "https://youtu.be/VYWclWI1W1g?si=NEk4Szc0tA40feiJ",
    "predicted": 100.0,
    "clearNotes": 110.0
  },
  {
    "type": "Flash",
    "unit": "셔플",
    "title": "타천사",
    "totalNotes": 158,
    "duration": "2:32",
    "etStart": null,
    "etEnd": null,
    "measured": null,
    "category": "others",
    "video": null,
    "predicted": 86.0,
    "clearNotes": 96.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "BRIGHTEST STARS!! (10주년)",
    "totalNotes": 188,
    "duration": "2:27",
    "etStart": 56,
    "etEnd": 73,
    "measured": 98,
    "category": "others",
    "video": "https://youtu.be/UqntUWTtpjM?si=C7iAnC2mjPdlK_fg",
    "predicted": 100.0,
    "clearNotes": 110.0
  },
  {
    "type": "Glitter",
    "unit": "콜라보",
    "title": "세이크리드 루인",
    "totalNotes": 234,
    "duration": "2:27",
    "etStart": 0,
    "etEnd": 0,
    "measured": 125,
    "category": "others",
    "video": "https://youtu.be/GuYM8DPXMvQ?si=MbjrJ9_U4KuugnEo",
    "predicted": 127.0,
    "clearNotes": 137.0
  },
  {
    "type": "Flash",
    "unit": "셔플",
    "title": "군연지원 (루리마츠리)",
    "totalNotes": 135,
    "duration": "2:42",
    "etStart": 72,
    "etEnd": 130,
    "measured": 72,
    "category": "others",
    "video": "https://youtu.be/jVyJe-QNo44?si=3w-vbS4s22BlxQLk",
    "predicted": 76.0,
    "clearNotes": 86.0
  },
  {
    "type": "All",
    "unit": "콜라보",
    "title": "RISE STAR'S SPIRITS (에리오스2)",
    "totalNotes": 215,
    "duration": "2:55",
    "etStart": 0,
    "etEnd": 0,
    "measured": 125,
    "category": "others",
    "video": "https://youtu.be/lGQHOxTyiy0?si=GRG9U3h0cFx6T_z2",
    "predicted": 116.0,
    "clearNotes": 126.0
  },
  {
    "type": "Flash",
    "unit": "셔플",
    "title": "쿠마쿠마 레스큐",
    "totalNotes": 236,
    "duration": "2:38",
    "etStart": 163,
    "etEnd": 191,
    "measured": 131,
    "category": "others",
    "video": "https://youtu.be/y5kr3aLLFvc?si=TwIgnQh_ArdGINnG",
    "predicted": 128.0,
    "clearNotes": 138.0
  },
  {
    "type": "Sparkle",
    "unit": "셔플_10주년",
    "title": "보쿠노 위크포인트 (1번 셔플)",
    "totalNotes": 111,
    "duration": "2:31",
    "etStart": 72,
    "etEnd": 99,
    "measured": 60,
    "category": "others",
    "video": "https://youtu.be/KFwxsDZRM9A?si=vV2YocFoYiHhLI1-",
    "predicted": 62.0,
    "clearNotes": 72.0
  },
  {
    "type": "Brilliant",
    "unit": "셔플_10주년",
    "title": "Graceful Punishment (5번 셔플)",
    "totalNotes": 138,
    "duration": "2:28",
    "etStart": 70,
    "etEnd": 84,
    "measured": 75,
    "category": "others",
    "video": "https://youtu.be/NI0Piax6irk?si=2_qHUnhCK70hVJ5b",
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Flash",
    "unit": "셔플_10주년",
    "title": "Deep into you (10번 셔플)",
    "totalNotes": 131,
    "duration": "2:27",
    "etStart": 34,
    "etEnd": 58,
    "measured": 65,
    "category": "others",
    "video": "https://youtu.be/tbQOph7J-8A?si=o4U7l2NqwyPq-Sgf",
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Flash",
    "unit": "셔플_10주년",
    "title": "러뷰&피스 전설 (3번 셔플)",
    "totalNotes": 229,
    "duration": "2:48",
    "etStart": 75,
    "etEnd": 134,
    "measured": 128,
    "category": "others",
    "video": "https://youtu.be/SEvHxWd77Cc?si=EQbbnTxJf4vxs9vT",
    "predicted": 124.0,
    "clearNotes": 134.0
  },
  {
    "type": "Glitter",
    "unit": "셔플_10주년",
    "title": "Ai$ 아이도루(8번 셔플)",
    "totalNotes": 244,
    "duration": "2:32",
    "etStart": 142,
    "etEnd": 206,
    "measured": 132,
    "category": "others",
    "video": "https://youtu.be/7Yn1DNogFtU?si=OMcESI8CFW0h9Otg",
    "predicted": 133.0,
    "clearNotes": 143.0
  },
  {
    "type": "Sparkle",
    "unit": "셔플_10주년",
    "title": "It's (k)not lov? (7번 셔플)",
    "totalNotes": 131,
    "duration": "2:42",
    "etStart": 56,
    "etEnd": 75,
    "measured": 71,
    "category": "others",
    "video": "https://youtu.be/-6NJnCkHlIg?si=NTyN4CVprzll_j0U",
    "predicted": 71.0,
    "clearNotes": 81.0
  },
  {
    "type": "Flash",
    "unit": "셔플_10주년",
    "title": "그것은 잔상의 소실점 2번",
    "totalNotes": 120,
    "duration": "2:39",
    "etStart": 26,
    "etEnd": 43,
    "measured": 66,
    "category": "others",
    "video": "https://youtu.be/PbXpKSAmNoQ?si=ht3jSujYglY6WHcj",
    "predicted": 64.0,
    "clearNotes": 74.0
  },
  {
    "type": "Sparkle",
    "unit": "진앤아",
    "title": "하나니나레",
    "totalNotes": 139,
    "duration": "2:21",
    "etStart": 58,
    "etEnd": 83,
    "measured": 76,
    "category": "others",
    "video": "https://youtu.be/-4pHM037Amg?si=Iw9FwIodUw8lZv1G",
    "predicted": 75.0,
    "clearNotes": 85.0
  },
  {
    "type": "Glitter",
    "unit": "셔플_10주년",
    "title": "9번 셔플",
    "totalNotes": 128,
    "duration": "2:37",
    "etStart": 61,
    "etEnd": 85,
    "measured": 73,
    "category": "others",
    "video": "https://youtu.be/GNsBVexvaAU?si=NlUnECKI_KsfKwxl",
    "predicted": 70.0,
    "clearNotes": 80.0
  },
  {
    "type": "Brilliant",
    "unit": "셔플_10주년",
    "title": "Fight is Only Fate (4번 셔플)",
    "totalNotes": 250,
    "duration": "2:39",
    "etStart": 162,
    "etEnd": 191,
    "measured": 132,
    "category": "others",
    "video": "https://youtu.be/pWZPZgVbcMM?si=zpI52u1HqwFY4zgr",
    "predicted": 136.0,
    "clearNotes": 146.0
  },
  {
    "type": "Sparkle",
    "unit": "셔플_10주년",
    "title": "프롤로그(プロローグのそのあとへ) 6번",
    "totalNotes": 144,
    "duration": "2:22",
    "etStart": 83,
    "etEnd": 109,
    "measured": 77,
    "category": "others",
    "video": "https://youtu.be/R83wURX7lwA?si=-06ZD0ViXPupk8by",
    "predicted": 79.0,
    "clearNotes": 89.0
  },
  {
    "type": "Brilliant",
    "unit": "콜라보",
    "title": "오보로(朧)",
    "totalNotes": 193,
    "duration": "2:11",
    "etStart": 0,
    "etEnd": 0,
    "measured": 104,
    "category": "others",
    "video": "https://youtu.be/_Qnf978dzwo?si=Lf4bo3rkKCNVo8xD",
    "predicted": 105.0,
    "clearNotes": 115.0
  },
  {
    "type": "All",
    "unit": "주년",
    "title": "브라스타 메가스피어",
    "totalNotes": 223,
    "duration": "2:30",
    "etStart": 0,
    "etEnd": 0,
    "measured": 122,
    "category": "others",
    "video": "https://youtu.be/4ViA8nIcIBk?si=gM-dhxmCLVcqFku2",
    "predicted": 121.0,
    "clearNotes": 131.0
  },
  {
    "type": "Flash",
    "unit": "만우절",
    "title": "페르소나 아비스",
    "totalNotes": 230,
    "duration": "2:37",
    "etStart": 122,
    "etEnd": 111,
    "measured": 122,
    "category": "others",
    "video": "https://youtu.be/xXfJwP6_-2Q",
    "predicted": 123.0,
    "clearNotes": 133.0
  }
];

const MODEL_PARAMS = {
  "intercept": -3.5209315575781517,
  "coefs": [
    0.5353517201187353,
    -3.4742239846282694,
    9.879014494989024
  ],
  "simpleCoef": 0.5278932445220397,
  "simpleInt": 2.525464136154781,
  "safetyMargin": 10,
  "meanEtStart": 0.4960435767251353,
  "meanEtEnd": 0.6613200950539918,
  "trainSize": 170,
  "r2": 0.9688153472615771,
  "mae": 2.647245228188573
};
